// master_db.js
// This is your fixed source of truth. 
// Every player has a permanent alias and position assigned.

window.masterCardDatabase = [
    // MLB
    { name: "Shohei Ohtani", sport: "mlb", pos: "DH", alias: "ShowTime" },
    { name: "Aaron Judge", sport: "mlb", pos: "OF", alias: "El Capitan" },
    { name: "Bobby Witt Jr", sport: "mlb", pos: "SS", alias: "Cooze" },
    { name: "Juan Soto", sport: "mlb", pos: "OF", alias: "Bam Soda" },
    { name: "Tarik Skubal", sport: "mlb", pos: "P", alias: "The Psycho" },
    { name: "Paul Skenes", sport: "mlb", pos: "P", alias: "Gigantor" },
    { name: "Francisco Lindor", sport: "mlb", pos: "SS", alias: "Smiley" },
    { name: "Jose Ramirez", sport: "mlb", pos: "3B", alias: "HotCornerBoss" },
    { name: "Gunnar Henderson", sport: "mlb", pos: "SS", alias: "BaltimoreBullet" },
    { name: "Yordan Alvarez", sport: "mlb", pos: "DH", alias: "TexasTitan" },
    { name: "Kyle Tucker", sport: "mlb", pos: "OF", alias: "AstroGlider" },
    { name: "Elly De La Cruz", sport: "mlb", pos: "SS", alias: "ElectricSlide" },
    { name: "Corbin Carroll", sport: "mlb", pos: "OF", alias: "Mr Outfield" },
    { name: "Bryce Harper", sport: "mlb", pos: "1B", alias: "PhillyPhrenzy" },
    { name: "Trea Turner", sport: "mlb", pos: "SS", alias: "SpeedDemon" },
    { name: "William Contreras", sport: "mlb", pos: "C", alias: "BackstopBruiser" },
    { name: "Chris Sale", sport: "mlb", pos: "P", alias: "SliderKing" },
    { name: "Logan Webb", sport: "mlb", pos: "P", alias: "BayAreaAce" },
    { name: "Will Smith", sport: "mlb", pos: "C", alias: "HollywoodCatcher" },
    { name: "Vladimir Guerrero Jr", sport: "mlb", pos: "1B", alias: "MapleMasher" },
    { name: "Adley Rutschman", sport: "mlb", pos: "C", alias: "CharmCityCatcher" },
    { name: "Corey Seager", sport: "mlb", pos: "SS", alias: "TexasRanger" },
    { name: "Freddie Freeman", sport: "mlb", pos: "1B", alias: "CaliFirstBase" },
    { name: "Zack Wheeler", sport: "mlb", pos: "P", alias: "PhillyFire" },
    { name: "Riley Greene", sport: "mlb", pos: "OF", alias: "MotorCityKid" },
    { name: "Jackson Chourio", sport: "mlb", pos: "OF", alias: "BrewCrewPhenom" },
    { name: "Paul Goldschmidt", sport: "mlb", pos: "1B", alias: "DesertGold" },
    { name: "Austin Riley", sport: "mlb", pos: "3B", alias: "ATL_Smasher" },
    { name: "Matt Olson", sport: "mlb", pos: "1B", alias: "BravesBomber" },
    { name: "Ozzie Albies", sport: "mlb", pos: "2B", alias: "SwitchHitter" },
    { name: "Luis Robert Jr", sport: "mlb", pos: "OF", alias: "LaPantera" },
    { name: "Fernando Tatis Jr", sport: "mlb", pos: "OF", alias: "ElNino" },
    { name: "Manny Machado", sport: "mlb", pos: "3B", alias: "The Agent" },
    { name: "Jackson Merrill", sport: "mlb", pos: "OF", alias: "RookieSensation" },
    { name: "Dylan Cease", sport: "mlb", pos: "P", alias: "StrikeoutMachine" },
    { name: "Cole Ragans", sport: "mlb", pos: "P", alias: "RoyalsAce" },
    { name: "Seth Lugo", sport: "mlb", pos: "P", alias: "CurveballKing" },
    { name: "George Kirby", sport: "mlb", pos: "P", alias: "ControlFreak" },
    { name: "Logan Gilbert", sport: "mlb", pos: "P", alias: "TallHurler" },
    { name: "Cal Raleigh", sport: "mlb", pos: "C", alias: "BigDumper" },
    { name: "Julio Rodriguez", sport: "mlb", pos: "OF", alias: "SeattleShow" },
    { name: "Luis Castillo", sport: "mlb", pos: "P", alias: "LaPiedra" },
    { name: "Framber Valdez", sport: "mlb", pos: "P", alias: "GroundballKing" },
    { name: "Kyle Schwarber", sport: "mlb", pos: "DH", alias: "OctoberBomber" },
    { name: "Nick Castellanos", sport: "mlb", pos: "OF", alias: "DeepDrive" },
    { name: "Cristopher Sanchez", sport: "mlb", pos: "P", alias: "PhillyLefty" },
    { name: "Ranger Suarez", sport: "mlb", pos: "P", alias: "IceColdLefty" },
    { name: "Zac Gallen", sport: "mlb", pos: "P", alias: "Milkman" },
    { name: "Ketel Marte", sport: "mlb", pos: "2B", alias: "DesertSwitch" },
    { name: "Christian Walker", sport: "mlb", pos: "1B", alias: "SnakeGlove" },
    { name: "Merrill Kelly", sport: "mlb", pos: "P", alias: "DesertAce" },
    { name: "Oneil Cruz", sport: "mlb", pos: "SS", alias: "BucsCannon" },
    { name: "Bryan Reynolds", sport: "mlb", pos: "OF", alias: "PirateSwitch" },
    { name: "Jared Jones", sport: "mlb", pos: "P", alias: "SteelCityGas" },
    { name: "Ke'Bryan Hayes", sport: "mlb", pos: "3B", alias: "GoldGlove3B" },
    { name: "Dansby Swanson", sport: "mlb", pos: "SS", alias: "WindyCitySS" },
    { name: "Shota Imanaga", sport: "mlb", pos: "P", alias: "RisingSunAce" },
    { name: "Justin Steele", sport: "mlb", pos: "P", alias: "WindyCityLefty" },
    { name: "Seiya Suzuki", sport: "mlb", pos: "OF", alias: "TokyoSlugger" },
    { name: "Pete Alonso", sport: "mlb", pos: "1B", alias: "PolarBear" },
    { name: "Kodai Senga", sport: "mlb", pos: "P", alias: "GhostFork" },
    { name: "Edwin Diaz", sport: "mlb", pos: "P", alias: "TrumpetCloser" },
    { name: "Brandon Nimmo", sport: "mlb", pos: "OF", alias: "SprintToFirst" },
    { name: "Mark Vientos", sport: "mlb", pos: "3B", alias: "MetsMasher" },
    { name: "Gerrit Cole", sport: "mlb", pos: "P", alias: "EmpireAce" },
    { name: "Giancarlo Stanton", sport: "mlb", pos: "DH", alias: "ExitVeloKing" },
    { name: "Anthony Volpe", sport: "mlb", pos: "SS", alias: "BronxKid" },
    { name: "Luis Gil", sport: "mlb", pos: "P", alias: "EmpireHeat" },
    { name: "Carlos Rodon", sport: "mlb", pos: "P", alias: "LeftyBronx" },
    { name: "Rafael Devers", sport: "mlb", pos: "3B", alias: "BostonMasher" },
    { name: "Triston Casas", sport: "mlb", pos: "1B", alias: "La Casa" },
    { name: "Ceddanne Rafaela", sport: "mlb", pos: "OF", alias: "CenterfieldNinja" },
    { name: "Tanner Houck", sport: "mlb", pos: "P", alias: "BostonSlider" },
    { name: "Brayan Bello", sport: "mlb", pos: "P", alias: "ChangeupArtist" },
    { name: "Bo Bichette", sport: "mlb", pos: "SS", alias: "FlowBro" },
    { name: "Kevin Gausman", sport: "mlb", pos: "P", alias: "SplitterGod" },
    { name: "Jose Berrios", sport: "mlb", pos: "P", alias: "LaMakina" },
    { name: "Daulton Varsho", sport: "mlb", pos: "OF", alias: "TorontoGlove" },
    { name: "Colton Cowser", sport: "mlb", pos: "OF", alias: "BirdBat" },
    { name: "Jordan Westburg", sport: "mlb", pos: "3B", alias: "Banana Man" },
    { name: "Grayson Rodriguez", sport: "mlb", pos: "P", alias: "BirdlandHeat" },
    { name: "Corbin Burnes", sport: "mlb", pos: "P", alias: "CutterKing" },
    { name: "Lane Thomas", sport: "mlb", pos: "OF", alias: "DCNinja" },
    { name: "Steven Kwan", sport: "mlb", pos: "OF", alias: "ContactKing" },
    { name: "Josh Naylor", sport: "mlb", pos: "1B", alias: "SmokeEater" },
    { name: "Emmanuel Clase", sport: "mlb", pos: "P", alias: "CutterCloser" },
    { name: "Tanner Bibee", sport: "mlb", pos: "P", alias: "GuardianAce" },
    { name: "Royce Lewis", sport: "mlb", pos: "3B", alias: "MinnesotaMasher" },
    { name: "Carlos Correa", sport: "mlb", pos: "SS", alias: "Groot" },
    { name: "Pablo Lopez", sport: "mlb", pos: "P", alias: "TwinCityAce" },
    { name: "Byron Buxton", sport: "mlb", pos: "OF", alias: "BuckTruck" },
    { name: "Joe Ryan", sport: "mlb", pos: "P", alias: "MustacheAce" },
    { name: "Wyatt Langford", sport: "mlb", pos: "OF", alias: "RangerRookie" },
    { name: "Evan Carter", sport: "mlb", pos: "OF", alias: "TexasKid" },
    { name: "Nathan Eovaldi", sport: "mlb", pos: "P", alias: "NastyNate" },
    { name: "Jacob deGrom", sport: "mlb", pos: "P", alias: "DeGrominator" },
    { name: "Marcus Semien", sport: "mlb", pos: "2B", alias: "IronMan2B" },
    { name: "Alvarez", sport: "mlb", pos: "C", alias: "HoustonCatcher" },
    { name: "Spencer Strider", sport: "mlb", pos: "P", alias: "Quadzilla" },
    { name: "Max Fried", sport: "mlb", pos: "P", alias: "CurveballLefty" },

    // NHL
    { name: "Connor McDavid", sport: "nhl", pos: "C", alias: "Legend" },
    { name: "Nathan MacKinnon", sport: "nhl", pos: "C", alias: "Natty" },
    { name: "Mikko Rantanen", sport: "nhl", pos: "RW", alias: "Mike Rat" },
    { name: "Auston Matthews", sport: "nhl", pos: "C", alias: "Matty A" },
    { name: "Cale Makar", sport: "nhl", pos: "D", alias: "Mr D" },
    { name: "Nikita Kucherov", sport: "nhl", pos: "RW", alias: "Mr Nasty" },
    { name: "Leon Draisaitl", sport: "nhl", pos: "C", alias: "Hitman" },
    { name: "Connor Hellebuyck", sport: "nhl", pos: "G", alias: "Goalmister" },
    { name: "Artemi Panarin", sport: "nhl", pos: "LW", alias: "The Loaf" },
    { name: "Quinn Hughes", sport: "nhl", pos: "D", alias: "Blueline Bandit" },
    { name: "Matthew Tkachuk", sport: "nhl", pos: "LW", alias: "The Agitator" },
    { name: "David Pastrnak", sport: "nhl", pos: "RW", alias: "The Noodle" },
    { name: "Sidney Crosby", sport: "nhl", pos: "C", alias: "The Kid" },
    { name: "Kirill Kaprizov", sport: "nhl", pos: "LW", alias: "Rocket" },
    { name: "Jack Hughes", sport: "nhl", pos: "C", alias: "The Second Sun" },
    { name: "Igor Shesterkin", sport: "nhl", pos: "G", alias: "Prodigy" },
    { name: "Aleksander Barkov", sport: "nhl", pos: "C", alias: "FinnishForce" },
    { name: "Adam Fox", sport: "nhl", pos: "D", alias: "FoxyDefense" },
    { name: "William Nylander", sport: "nhl", pos: "RW", alias: "WillyStyles" },
    { name: "Sebastian Aho", sport: "nhl", pos: "C", alias: "Fishy" },
    { name: "Jack Eichel", sport: "nhl", pos: "C", alias: "VegasCenter" },
    { name: "Mitch Marner", sport: "nhl", pos: "RW", alias: "MagicMitch" },
    { name: "Elias Pettersson", sport: "nhl", pos: "C", alias: "Alien" },
    { name: "Sam Reinhart", sport: "nhl", pos: "RW", alias: "PantherSniper" },
    { name: "Zach Hyman", sport: "nhl", pos: "LW", alias: "ZachAttack" },
    { name: "J.T. Miller", sport: "nhl", pos: "C", alias: "CanucksBoss" },
    { name: "Jason Robertson", sport: "nhl", pos: "LW", alias: "Robo" },
    { name: "Jake Oettinger", sport: "nhl", pos: "G", alias: "Otter" },
    { name: "Roman Josi", sport: "nhl", pos: "D", alias: "SwissNorris" },
    { name: "Victor Hedman", sport: "nhl", pos: "D", alias: "LightningGiant" },
    { name: "Brady Tkachuk", sport: "nhl", pos: "LW", alias: "SensCaptain" },
    { name: "Rasmus Dahlin", sport: "nhl", pos: "D", alias: "BuffaloBlueline" },
    { name: "Miro Heiskanen", sport: "nhl", pos: "D", alias: "FinnishSkater" },
    { name: "Kyle Connor", sport: "nhl", pos: "LW", alias: "JetsSniper" },
    { name: "Juuse Saros", sport: "nhl", pos: "G", alias: "Juice" },
    { name: "Brock Boeser", sport: "nhl", pos: "RW", alias: "CanucksWinger" },
    { name: "Nick Suzuki", sport: "nhl", pos: "C", alias: "HabsCaptain" },
    { name: "Cole Caufield", sport: "nhl", pos: "LW", alias: "GoalCaufield" },
    { name: "Wyatt Johnston", sport: "nhl", pos: "C", alias: "DallasKid" },
    { name: "Roope Hintz", sport: "nhl", pos: "C", alias: "FinnishFlash2" },
    { name: "Travis Konecny", sport: "nhl", pos: "RW", alias: "TK" },
    { name: "Filip Forsberg", sport: "nhl", pos: "LW", alias: "Scoresberg" },
    { name: "Adrian Kempe", sport: "nhl", pos: "RW", alias: "KingsWinger" },
    { name: "Anze Kopitar", sport: "nhl", pos: "C", alias: "Kopi" },
    { name: "Noah Hanifin", sport: "nhl", pos: "D", alias: "VegasBlueline" },
    { name: "Alex Pietrangelo", sport: "nhl", pos: "D", alias: "VegasDefense" },
    { name: "Mark Stone", sport: "nhl", pos: "RW", alias: "VegasCaptain" },
    { name: "Connor Bedard", sport: "nhl", pos: "C", alias: "GenerationalTalent" },
    { name: "Tim Stutzle", sport: "nhl", pos: "C", alias: "JimmyStu" },
    { name: "Jake Guentzel", sport: "nhl", pos: "LW", alias: "LightningSniper" },
    { name: "Bo Horvat", sport: "nhl", pos: "C", alias: "IslesCenter" },
    { name: "Mathew Barzal", sport: "nhl", pos: "RW", alias: "IslesSpeed" },
    { name: "Noah Dobson", sport: "nhl", pos: "D", alias: "IslesBlueline" },
    { name: "Brayden Point", sport: "nhl", pos: "C", alias: "Pointer" },
    { name: "Charlie McAvoy", sport: "nhl", pos: "D", alias: "BostonBlueline" },
    { name: "Jeremy Swayman", sport: "nhl", pos: "G", alias: "Sway" },
    { name: "Brad Marchand", sport: "nhl", pos: "LW", alias: "TheRat" },
    { name: "Chris Kreider", sport: "nhl", pos: "LW", alias: "Kreids" },
    { name: "Vincent Trocheck", sport: "nhl", pos: "C", alias: "EmpireCenter" },
    { name: "Seth Jarvis", sport: "nhl", pos: "RW", alias: "Jarvy" },
    { name: "Andrei Vasilevskiy", sport: "nhl", pos: "G", alias: "BigCat" },
    { name: "Sergei Bobrovsky", sport: "nhl", pos: "G", alias: "OfficerBob" },
    { name: "Josh Morrissey", sport: "nhl", pos: "D", alias: "JetsBlueline" },
    { name: "Mark Scheifele", sport: "nhl", pos: "C", alias: "JetsCenter" },
    { name: "Nico Hischier", sport: "nhl", pos: "C", alias: "DevilsCaptain" },
    { name: "Jesper Bratt", sport: "nhl", pos: "LW", alias: "DevilsSpeed" },
    { name: "Tage Thompson", sport: "nhl", pos: "C", alias: "TNT" },
    { name: "Alex Ovechkin", sport: "nhl", pos: "LW", alias: "GreatEight" },
    { name: "Dylan Larkin", sport: "nhl", pos: "C", alias: "MotorCityCaptain" },
    { name: "Lucas Raymond", sport: "nhl", pos: "RW", alias: "MotorCityWinger" },
    { name: "Moritz Seider", sport: "nhl", pos: "D", alias: "MoSeider" },
    { name: "Robert Thomas", sport: "nhl", pos: "C", alias: "BluesPlaymaker" },
    { name: "Jordan Kyrou", sport: "nhl", pos: "RW", alias: "BluesSpeed" },
    { name: "Frank Vatrano", sport: "nhl", pos: "LW", alias: "FrankTheTank" },
    { name: "Mason McTavish", sport: "nhl", pos: "C", alias: "DucksCenter" },
    { name: "Macklin Celebrini", sport: "nhl", pos: "C", alias: "SharksRookie" },
    { name: "Logan Thompson", sport: "nhl", pos: "G", alias: "CapsWall" },
    { name: "Thatcher Demko", sport: "nhl", pos: "G", alias: "Demko" },
    { name: "Tomas Hertl", sport: "nhl", pos: "C", alias: "FunMustBeAlways" },
    { name: "Joel Eriksson Ek", sport: "nhl", pos: "C", alias: "WildCenter" },
    { name: "Matt Boldy", sport: "nhl", pos: "RW", alias: "WildWinger" },
    { name: "Brock Faber", sport: "nhl", pos: "D", alias: "WildBlueline" },
    { name: "Owen Power", sport: "nhl", pos: "D", alias: "BuffaloRookieD" },
    { name: "Juraj Slafkovsky", sport: "nhl", pos: "LW", alias: "Slaf" },
    { name: "Quinton Byfield", sport: "nhl", pos: "C", alias: "KingsGiant" },
    { name: "Kevin Fiala", sport: "nhl", pos: "LW", alias: "KingsPlaymaker" },
    { name: "Carter Verhaeghe", sport: "nhl", pos: "LW", alias: "PantherClutch" },
    { name: "Gustav Forsling", sport: "nhl", pos: "D", alias: "PantherDefense" },
    { name: "Teuvo Teravainen", sport: "nhl", pos: "LW", alias: "HawksWinger" },
    { name: "Seth Jones", sport: "nhl", pos: "D", alias: "HawksBlueline" },
    { name: "John Tavares", sport: "nhl", pos: "C", alias: "JT" },
    { name: "Morgan Rielly", sport: "nhl", pos: "D", alias: "MoRielly" },
    { name: "Nazem Kadri", sport: "nhl", pos: "C", alias: "FlamesCenter" },
    { name: "MacKenzie Weegar", sport: "nhl", pos: "D", alias: "FlamesDefense" },
    { name: "Rasmus Andersson", sport: "nhl", pos: "D", alias: "FlamesBlueline" },
    { name: "Ukko-Pekka Luukkonen", sport: "nhl", pos: "G", alias: "UPL" },
    { name: "Jordan Binnington", sport: "nhl", pos: "G", alias: "Binner" },
    { name: "Charlie Lindgren", sport: "nhl", pos: "G", alias: "Chuckies" },
    { name: "John Carlson", sport: "nhl", pos: "D", alias: "CapsDefense" },
    { name: "Dylan Strome", sport: "nhl", pos: "C", alias: "CapsCenter" },

    // NBA
    { name: "Nikola Jokic", sport: "nba", pos: "C", alias: "TheJoker" },
    { name: "Luka Doncic", sport: "nba", pos: "G", alias: "LukaMagic" },
    { name: "Shai Gilgeous-Alexander", sport: "nba", pos: "G", alias: "SGA" },
    { name: "Giannis Antetokounmpo", sport: "nba", pos: "F", alias: "GreekFreak" },
    { name: "Joel Embiid", sport: "nba", pos: "C", alias: "TheProcess" },
    { name: "Jayson Tatum", sport: "nba", pos: "F", alias: "BostonStar" },
    { name: "Anthony Edwards", sport: "nba", pos: "G", alias: "AntMan" },
    { name: "Victor Wembanyama", sport: "nba", pos: "C", alias: "AlienCenter" },
    { name: "Stephen Curry", sport: "nba", pos: "G", alias: "ChefCurry" },
    { name: "Kevin Durant", sport: "nba", pos: "F", alias: "SlimReaper" },
    { name: "LeBron James", sport: "nba", pos: "F", alias: "TheKing" },
    { name: "Devin Booker", sport: "nba", pos: "G", alias: "D_Book" },
    { name: "Anthony Davis", sport: "nba", pos: "C", alias: "TheBrow" },
    { name: "Jalen Brunson", sport: "nba", pos: "G", alias: "EmpirePoint" },
    { name: "Tyrese Haliburton", sport: "nba", pos: "G", alias: "IndyPasser" },
    { name: "Kawhi Leonard", sport: "nba", pos: "F", alias: "TheClaw" },
    { name: "Ja Morant", sport: "nba", pos: "G", alias: "GrizzlyFlyer" },
    { name: "Donovan Mitchell", sport: "nba", pos: "G", alias: "Spida" },
    { name: "Bam Adebayo", sport: "nba", pos: "C", alias: "MiamiAnchor" },
    { name: "Jaylen Brown", sport: "nba", pos: "G", alias: "BostonWing" },
    { name: "Domantas Sabonis", sport: "nba", pos: "C", alias: "SacTownBig" },
    { name: "De'Aaron Fox", sport: "nba", pos: "G", alias: "SwipaTheFox" },
    { name: "Tyrese Maxey", sport: "nba", pos: "G", alias: "PhillySpeed" },
    { name: "Jimmy Butler", sport: "nba", pos: "F", alias: "JimmyBuckets" },
    { name: "Paul George", sport: "nba", pos: "F", alias: "PG13" },
    { name: "Kyrie Irving", sport: "nba", pos: "G", alias: "UncleDrew" },
    { name: "Chet Holmgren", sport: "nba", pos: "C", alias: "OKC_Tower" },
    { name: "Paolo Banchero", sport: "nba", pos: "F", alias: "MagicForward" },
    { name: "Damian Lillard", sport: "nba", pos: "G", alias: "DameTime" },
    { name: "Lauri Markkanen", sport: "nba", pos: "F", alias: "Finnisher" },
    { name: "Karl-Anthony Towns", sport: "nba", pos: "C", alias: "KAT" },
    { name: "Rudy Gobert", sport: "nba", pos: "C", alias: "StifleTower" },
    { name: "Jaren Jackson Jr", sport: "nba", pos: "F", alias: "BlockPanther" },
    { name: "Jamal Murray", sport: "nba", pos: "G", alias: "BlueArrow" },
    { name: "James Harden", sport: "nba", pos: "G", alias: "TheBeard" },
    { name: "Zion Williamson", sport: "nba", pos: "F", alias: "Zanos" },
    { name: "Brandon Ingram", sport: "nba", pos: "F", alias: "PelicanWing" },
    { name: "Pascal Siakam", sport: "nba", pos: "F", alias: "SpicyP" },
    { name: "Cade Cunningham", sport: "nba", pos: "G", alias: "MotorCityPoint" },
    { name: "Scottie Barnes", sport: "nba", pos: "F", alias: "TorontoStar" },
    { name: "Franz Wagner", sport: "nba", pos: "F", alias: "MagicWing" },
    { name: "Jalen Williams", sport: "nba", pos: "F", alias: "J_Dub" },
    { name: "Alperen Sengun", sport: "nba", pos: "C", alias: "HoustonBig" },
    { name: "Darius Garland", sport: "nba", pos: "G", alias: "CavsPoint" },
    { name: "Evan Mobley", sport: "nba", pos: "F", alias: "CavsTower" },
    { name: "Mikal Bridges", sport: "nba", pos: "F", alias: "BrooklynBridge" },
    { name: "Derrick White", sport: "nba", pos: "G", alias: "BostonBaldy" },
    { name: "Kristaps Porzingis", sport: "nba", pos: "C", alias: "Unicorn" },
    { name: "Jrue Holiday", sport: "nba", pos: "G", alias: "BostonLockdown" },
    { name: "Aaron Gordon", sport: "nba", pos: "F", alias: "DenverDunker" },
    { name: "Michael Porter Jr", sport: "nba", pos: "F", alias: "MPJ" },
    { name: "Dejounte Murray", sport: "nba", pos: "G", alias: "PelicanGuard" },
    { name: "C.J. McCollum", sport: "nba", pos: "G", alias: "PelicanVeteran" },
    { name: "Immanuel Quickley", sport: "nba", pos: "G", alias: "TorontoPoint" },
    { name: "R.J. Barrett", sport: "nba", pos: "F", alias: "TorontoWing" },
    { name: "Fred VanVleet", sport: "nba", pos: "G", alias: "SteadyFreddy" },
    { name: "Jalen Green", sport: "nba", pos: "G", alias: "HoustonFlyer" },
    { name: "Jabari Smith Jr", sport: "nba", pos: "F", alias: "HoustonForward" },
    { name: "Keegan Murray", sport: "nba", pos: "F", alias: "SacTownWing" },
    { name: "Miles Bridges", sport: "nba", pos: "F", alias: "CharlotteDunker" },
    { name: "LaMelo Ball", sport: "nba", pos: "G", alias: "Melo" },
    { name: "Brandon Miller", sport: "nba", pos: "F", alias: "CharlotteRookie" },
    { name: "Trae Young", sport: "nba", pos: "G", alias: "IceTrae" },
    { name: "Jalen Johnson", sport: "nba", pos: "F", alias: "ATL_Forward" },
    { name: "Cam Thomas", sport: "nba", pos: "G", alias: "BrooklynScorer" },
    { name: "Nic Claxton", sport: "nba", pos: "C", alias: "BrooklynBlocker" },
    { name: "OG Anunoby", sport: "nba", pos: "F", alias: "EmpireLockdown" },
    { name: "Julius Randle", sport: "nba", pos: "F", alias: "EmpirePowerF" },
    { name: "Josh Hart", sport: "nba", pos: "G", alias: "EmpireHustle" },
    { name: "Donte DiVincenzo", sport: "nba", pos: "G", alias: "EmpireShooter" },
    { name: "Naz Reid", sport: "nba", pos: "C", alias: "NazReid" },
    { name: "Jaden McDaniels", sport: "nba", pos: "F", alias: "WolvesLockdown" },
    { name: "Myles Turner", sport: "nba", pos: "C", alias: "IndyBlocker" },
    { name: "Kyle Kuzma", sport: "nba", pos: "F", alias: "CapitalForward" },
    { name: "Jordan Poole", sport: "nba", pos: "G", alias: "CapitalGuard" },
    { name: "Alex Sarr", sport: "nba", pos: "C", alias: "CapitalRookie" },
    { name: "Tyler Herro", sport: "nba", pos: "G", alias: "BoyWonder" },
    { name: "Terry Rozier", sport: "nba", pos: "G", alias: "ScaryTerry" },
    { name: "Coby White", sport: "nba", pos: "G", alias: "WindyCityGuard" },
    { name: "Josh Giddey", sport: "nba", pos: "G", alias: "WindyCityPasser" },
    { name: "Zach LaVine", sport: "nba", pos: "G", alias: "WindyCityFlyer" },
    { name: "Nikola Vucevic", sport: "nba", pos: "C", alias: "WindyCityBig" },
    { name: "Jerami Grant", sport: "nba", pos: "F", alias: "RipCityForward" },
    { name: "Anfernee Simons", sport: "nba", pos: "G", alias: "RipCityShooter" },
    { name: "Scoot Henderson", sport: "nba", pos: "G", alias: "RipCityPoint" },
    { name: "Deandre Ayton", sport: "nba", pos: "C", alias: "RipCityBig" },
    { name: "Draymond Green", sport: "nba", pos: "F", alias: "WarriorHeart" },
    { name: "Jonathan Kuminga", sport: "nba", pos: "F", alias: "WarriorFlyer" },
    { name: "Austin Reaves", sport: "nba", pos: "G", alias: "LAL_Shooter" },
    { name: "Rui Hachimura", sport: "nba", pos: "F", alias: "LAL_Forward" },
    { name: "D'Angelo Russell", sport: "nba", pos: "G", alias: "D_Lo" },
    { name: "Desmond Bane", sport: "nba", pos: "G", alias: "GrizzlyShooter" },
    { name: "Marcus Smart", sport: "nba", pos: "G", alias: "GrizzlyHeart" },
    { name: "Khris Middleton", sport: "nba", pos: "F", alias: "BucksClutch" },
    { name: "Bobby Portis", sport: "nba", pos: "F", alias: "BucksEnergy" },
    { name: "Walker Kessler", sport: "nba", pos: "C", alias: "JazzBlocker" },
    { name: "Keyonte George", sport: "nba", pos: "G", alias: "JazzGuard" },
    { name: "Tre Jones", sport: "nba", pos: "G", alias: "SpursPoint" },
    { name: "Jeremy Sochan", sport: "nba", pos: "F", alias: "SpursEnergy" },
    { name: "Chris Paul", sport: "nba", pos: "G", alias: "PointGod" },

    // NFL
    { name: "Patrick Mahomes", sport: "nfl", pos: "QB", alias: "Showtime_QB" },
    { name: "Lamar Jackson", sport: "nfl", pos: "QB", alias: "ActionJackson" },
    { name: "Christian McCaffrey", sport: "nfl", pos: "RB", alias: "Run_CMC" },
    { name: "Justin Jefferson", sport: "nfl", pos: "WR", alias: "Jets" },
    { name: "Tyreek Hill", sport: "nfl", pos: "WR", alias: "Cheetah" },
    { name: "Myles Garrett", sport: "nfl", pos: "DE", alias: "ClevelandBeast" },
    { name: "T.J. Watt", sport: "nfl", pos: "LB", alias: "SteelCityRush" },
    { name: "Josh Allen", sport: "nfl", pos: "QB", alias: "BuffaloCannon" },
    { name: "CeeDee Lamb", sport: "nfl", pos: "WR", alias: "DallasStarWR" },
    { name: "Sauce Gardner", sport: "nfl", pos: "CB", alias: "LostInTheSauce" },
    { name: "Micah Parsons", sport: "nfl", pos: "LB", alias: "DallasLion" },
    { name: "Joe Burrow", sport: "nfl", pos: "QB", alias: "JoeyB" },
    { name: "Ja'Marr Chase", sport: "nfl", pos: "WR", alias: "CincyStarWR" },
    { name: "A.J. Brown", sport: "nfl", pos: "WR", alias: "PhillyAlpha" },
    { name: "Penei Sewell", sport: "nfl", pos: "OT", alias: "MotorCityWall" },
    { name: "Trent Williams", sport: "nfl", pos: "OT", alias: "Silverback" },
    { name: "Fred Warner", sport: "nfl", pos: "LB", alias: "BayAreaLB" },
    { name: "Nick Bosa", sport: "nfl", pos: "DE", alias: "BayAreaRush" },
    { name: "Chris Jones", sport: "nfl", pos: "DT", alias: "KC_StoneWall" },
    { name: "Amon-Ra St. Brown", sport: "nfl", pos: "WR", alias: "SunGod" },
    { name: "Jared Goff", sport: "nfl", pos: "QB", alias: "MotorCityQB" },
    { name: "Brock Purdy", sport: "nfl", pos: "QB", alias: "MrRelevant" },
    { name: "Jalen Hurts", sport: "nfl", pos: "QB", alias: "PhillyLeader" },
    { name: "Jordan Love", sport: "nfl", pos: "QB", alias: "CheeseheadQB" },
    { name: "C.J. Stroud", sport: "nfl", pos: "QB", alias: "TexasRookieQB" },
    { name: "Nico Collins", sport: "nfl", pos: "WR", alias: "TexasDeepThreat" },
    { name: "Davante Adams", sport: "nfl", pos: "WR", alias: "VegasRouteKing" },
    { name: "Maxx Crosby", sport: "nfl", pos: "DE", alias: "MadMaxx" },
    { name: "Aidan Hutchinson", sport: "nfl", pos: "DE", alias: "Hutch" },
    { name: "Kyle Hamilton", sport: "nfl", pos: "S", alias: "CharmCitySafety" },
    { name: "Roquan Smith", sport: "nfl", pos: "LB", alias: "CharmCityLB" },
    { name: "George Kittle", sport: "nfl", pos: "TE", alias: "BayAreaTE" },
    { name: "Travis Kelce", sport: "nfl", pos: "TE", alias: "KC_TightEnd" },
    { name: "Sam LaPorta", sport: "nfl", pos: "TE", alias: "MotorCityTE" },
    { name: "Breece Hall", sport: "nfl", pos: "RB", alias: "EmpireStateRB" },
    { name: "Saquon Barkley", sport: "nfl", pos: "RB", alias: "PhillyNewRB" },
    { name: "Bijan Robinson", sport: "nfl", pos: "RB", alias: "ATL_StarRB" },
    { name: "Jahmyr Gibbs", sport: "nfl", pos: "RB", alias: "MotorCitySpeed" },
    { name: "Garrett Wilson", sport: "nfl", pos: "WR", alias: "EmpireStateWR" },
    { name: "Drake London", sport: "nfl", pos: "WR", alias: "ATL_Tower" },
    { name: "Puka Nacua", sport: "nfl", pos: "WR", alias: "LA_RookieWR" },
    { name: "Cooper Kupp", sport: "nfl", pos: "WR", alias: "LA_TripleCrown" },
    { name: "Kyren Williams", sport: "nfl", pos: "RB", alias: "LA_Workhorse" },
    { name: "DK Metcalf", sport: "nfl", pos: "WR", alias: "SeattleCyborg" },
    { name: "Justin Madubuike", sport: "nfl", pos: "DT", alias: "CharmCityDT" },
    { name: "Antoine Winfield Jr", sport: "nfl", pos: "S", alias: "PirateSafety" },
    { name: "Mike Evans", sport: "nfl", pos: "WR", alias: "PirateTower" },
    { name: "Baker Mayfield", sport: "nfl", pos: "QB", alias: "PirateBaker" },
    { name: "Jaylen Waddle", sport: "nfl", pos: "WR", alias: "MiamiPenguin" },
    { name: "Jalen Ramsey", sport: "nfl", pos: "CB", alias: "MiamiIsland" },
    { name: "Patrick Surtain II", sport: "nfl", pos: "CB", alias: "DenverIsland" },
    { name: "Quinnen Williams", sport: "nfl", pos: "DT", alias: "EmpireStateDT" },
    { name: "Dexter Lawrence", sport: "nfl", pos: "DT", alias: "SexyDexy" },
    { name: "Brian Burns", sport: "nfl", pos: "LB", alias: "GiantRush" },
    { name: "Malik Nabers", sport: "nfl", pos: "WR", alias: "GiantRookie" },
    { name: "Kayvon Thibodeaux", sport: "nfl", pos: "DE", alias: "GiantEdge" },
    { name: "Josh Hines-Allen", sport: "nfl", pos: "LB", alias: "DuvalRush" },
    { name: "Trevor Lawrence", sport: "nfl", pos: "QB", alias: "DuvalPrince" },
    { name: "Tua Tagovailoa", sport: "nfl", pos: "QB", alias: "MiamiLefty" },
    { name: "Raheem Mostert", sport: "nfl", pos: "RB", alias: "MiamiSpeed" },
    { name: "Deebo Samuel", sport: "nfl", pos: "WR", alias: "BayAreaDeebo" },
    { name: "Brandon Aiyuk", sport: "nfl", pos: "WR", alias: "BayAreaRoute" },
    { name: "Christian Darrisaw", sport: "nfl", pos: "OT", alias: "MinnesotaWall" },
    { name: "Danielle Hunter", sport: "nfl", pos: "DE", alias: "TexasEdge" },
    { name: "Will Anderson Jr", sport: "nfl", pos: "DE", alias: "TexasRookieEdge" },
    { name: "Derek Stingley Jr", sport: "nfl", pos: "CB", alias: "TexasIsland" },
    { name: "Laremy Tunsil", sport: "nfl", pos: "OT", alias: "TexasWall" },
    { name: "Rashawn Slater", sport: "nfl", pos: "OT", alias: "LA_BoltWall" },
    { name: "Justin Herbert", sport: "nfl", pos: "QB", alias: "LA_BoltCannon" },
    { name: "Joe Alt", sport: "nfl", pos: "OT", alias: "LA_BoltRookie" },
    { name: "Derwin James", sport: "nfl", pos: "S", alias: "LA_BoltSafety" },
    { name: "Khalil Mack", sport: "nfl", pos: "LB", alias: "LA_BoltRush" },
    { name: "Jayden Daniels", sport: "nfl", pos: "QB", alias: "CapitalRookieQB" },
    { name: "Terry McLaurin", sport: "nfl", pos: "WR", alias: "ScaryTerryWR" },
    { name: "Caleb Williams", sport: "nfl", pos: "QB", alias: "WindyCityRookie" },
    { name: "DJ Moore", sport: "nfl", pos: "WR", alias: "WindyCityWR" },
    { name: "Keenan Allen", sport: "nfl", pos: "WR", alias: "WindyCityRoute" },
    { name: "Rome Odunze", sport: "nfl", pos: "WR", alias: "WindyCityDraft" },
    { name: "Montez Sweat", sport: "nfl", pos: "DE", alias: "WindyCityEdge" },
    { name: "Jaylon Johnson", sport: "nfl", pos: "CB", alias: "WindyCityIsland" },
    { name: "Kyler Murray", sport: "nfl", pos: "QB", alias: "DesertGamer" },
    { name: "Marvin Harrison Jr", sport: "nfl", pos: "WR", alias: "DesertRookie" },
    { name: "Budda Baker", sport: "nfl", pos: "S", alias: "DesertSafety" },
    { name: "Kirk Cousins", sport: "nfl", pos: "QB", alias: "ATL_Captain" },
    { name: "Kyle Pitts", sport: "nfl", pos: "TE", alias: "ATL_Unicorn" },
    { name: "Jessie Bates III", sport: "nfl", pos: "S", alias: "ATL_Safety" },
    { name: "DaRon Bland", sport: "nfl", pos: "CB", alias: "DallasPickSix" },
    { name: "Trevon Diggs", sport: "nfl", pos: "CB", alias: "DallasIsland" },
    { name: "Dak Prescott", sport: "nfl", pos: "QB", alias: "DallasLeader" },
    { name: "Jordan Addison", sport: "nfl", pos: "WR", alias: "MinnesotaWR2" },
    { name: "Aaron Jones", sport: "nfl", pos: "RB", alias: "MinnesotaNewRB" },
    { name: "Brian Thomas Jr", sport: "nfl", pos: "WR", alias: "DuvalRookie" },
    { name: "Xavier Worthy", sport: "nfl", pos: "WR", alias: "KC_Speed" },
    { name: "Trent McDuffie", sport: "nfl", pos: "CB", alias: "KC_Island" },
    { name: "George Karlaftis", sport: "nfl", pos: "DE", alias: "FuriousGeorge" },
    { name: "Jaycee Horn", sport: "nfl", pos: "CB", alias: "CarolinaIsland" },
    { name: "Derrick Brown", sport: "nfl", pos: "DT", alias: "CarolinaDT" },
    { name: "Stefon Diggs", sport: "nfl", pos: "WR", alias: "TexasStarWR" },
    { name: "Tank Dell", sport: "nfl", pos: "WR", alias: "TexasTank" },
    { name: "Joe Mixon", sport: "nfl", pos: "RB", alias: "TexasNewRB" }
];